version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "Microsoft.AspNetCore.Authentication.OpenIdConnect"
    versions: ["4.x", "5.x"]
  - dependency-name: "Microsoft.AspNetCore.Authentication.JwtBearer"
    versions: ["4.x", "5.x"]